// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package inject

import (
	"github.com/julienschmidt/httprouter"
	"worksample-go-layered-architecture/app/application/user"
	"worksample-go-layered-architecture/app/controller/v1"
	"worksample-go-layered-architecture/app/infrastructure/inmemory"
)

// Injectors from Injector.mock.go:

func Setup(router *httprouter.Router) *v1.UserController {
	userRepository := inmemory.NewUserRepository()
	getInteractor := user.NewGetInteractor(userRepository)
	userController := v1.NewUserController(getInteractor, router)
	return userController
}
